---
# Source: fluent-bit/templates/overlays/MODIF_ENV/kustomization.yaml
# Example configuration for the webserver
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test1-1

bases:
- ../../../base

resources:
- namespace.yaml
- networkpolicy.yaml

annotations:
