---
# Source: fluent-bit/templates/overlays/MODIF_ENV/kustomization.yaml
# Example configuration for the webserver
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

bases:
  - ../../base

configMapGenerator:
- name: config
  files:
    - configs/config

secretGenerator:
- name: memberlist
  files:
    - configs/secretkey

generatorOptions:
 disableNameSuffixHash: true